// GENERATED by scripts/gen-sdk-types.mts from gaiadesk-client's JSON Schema — do not edit.
// The result, error, request and event types of gaiadesk-client and `gaiadesk-cli --json`.

/** `token revoke --account --json`. */
export interface AccountRevoked {
  desk: string;
  message: string;
  ok: boolean;
}

/** `agent-connect --json`. */
export interface AgentCheck {
  desk_id: string;
  ok: boolean;
  screenshot: ScreenSize;
}

/** One entry of a desk's agent audit log, as its owner reads it. */
export interface AuditEvent {
  /** `connect`, `exec`, `exec.end`, `cp.upload`, `cp.download`, `forward`,
   * `job.start`, `job.kill`, `refused`. */
  action: string;
  at_ms: number;
  bytes?: number;
  /** Where it ran (`exec`, `job.start`). */
  cwd?: string | null;
  desk: string;
  /** The command line, the paths, `host:port`, the job. */
  detail: string;
  duration_ms?: number | null;
  /** `exec.end`: the command's exit code and how long it ran. */
  exit_code?: number | null;
  /** The token's name and non-secret id. */
  token: string;
  token_id: string;
}

/** `audit --json`, newest first. */
export interface AuditLog {
  events: Array<AuditEvent>;
}

/** A mouse button. */
export type Button = "left" | "right" | "middle";

export interface CopyFailure {
  message: string;
  path: string;
}

/** What a copy is doing, as it goes (`Desk::cp_up_with_progress`). */
export type CopyProgress = {
  event: "file_done";
  path: string;
  resumed: number;
  size: number;
} | {
  event: "file_failed";
  message: string;
  path: string;
} | {
  done: number;
  event: "bytes";
  path: string;
  size: number;
};

/** What a copy did — the `--json` summary. */
export interface CopyResult {
  /** Bytes this run moved. */
  bytes: number;
  desk: string;
  /** Where it landed (a desk path for an upload, a local one for a download). */
  destination: string;
  direction: string;
  dirs: number;
  failed: Array<CopyFailure>;
  files: number;
  /** Bytes already there from an earlier, interrupted run. */
  resumed_bytes: number;
  seconds: number;
}

/** What a desk is doing right now (`gaiadesk-cli stats`,
 * `DataMessage::Stats`). Every number is a snapshot taken when
 * asked. */
export interface DeskStats {
  /** Busy share of the whole machine, 0–100, over a short sample. */
  cpu_percent: number;
  /** Logical CPUs. */
  cpus: number;
  /** Every mounted volume worth listing, with its free space. */
  disks?: Array<DiskStat>;
  hostname: string;
  /** Background jobs (`gaiadesk-cli run --detach`) running now. */
  jobs_running: number;
  /** 1, 5 and 15 minute load averages. `None` where the OS has none (Windows). */
  load?: Array<number> | null;
  /** What programs can still have without swapping ("available"). */
  mem_free_mb: number;
  mem_total_mb: number;
  /** `macos`, `windows`, `linux` (`std::env::consts::OS`). */
  os: string;
  /** The OS's own name and version (`macOS 15.1`, `Windows 11 (26100)`). */
  os_version?: string;
  uptime_secs: number;
}

/** One desk, as listed. */
export interface Device {
  /** Its owner's app says it starts with the computer and works at the
   * lock screen (`None`: not said). */
  anytime?: boolean | null;
  /** The GaiaDesk version it last registered with (the server's list only). */
  app_version?: string | null;
  desk_id: string;
  /** The last one that failed, and why. */
  last_failure?: ReachFailure | null;
  /** The last connect from this machine that worked (`cli_reach`). */
  last_ok?: ReachSuccess | null;
  /** Seconds since the epoch. */
  last_seen?: number | null;
  name?: string | null;
  /** `Some(true)` online, `Some(false)` offline, `None` unknown. */
  online?: boolean | null;
  os?: string | null;
  /** Whose desk: "you", a teammate's email, or unknown. */
  owner?: string | null;
  probe?: ProbeResult | null;
  /** Reachable NOW: only with `--probe` (else `null`). */
  reachable?: boolean | null;
  /** Seconds since the server last heard the desk's socket (online desks,
   * a server that says). Long silence on an "online" desk: a dead socket. */
  signal_idle_secs?: number | null;
  /** Where this desk was found: "account", "team", "lan", "mesh", "recent". */
  sources: Array<string>;
}

/** `devices --json`. */
export interface DeviceList {
  devices: Array<Device>;
  /** Who this machine is signed in as, and where that came from — the
   * account whose desks the server listed. */
  identity: Identity;
  notes: Array<string>;
  /** Which sources answered: `server`, `lan`, `mesh`, `recent`. */
  sources: Array<string>;
}

/** Which way the content moves. */
export type Direction = "up" | "down" | "left" | "right";

/** `disconnect --json`. */
export interface Disconnected {
  closed: Array<string>;
}

/** One volume in `DeskStats`. */
export interface DiskStat {
  free_mb: number;
  /** Where it is mounted (`/`, `C:\\`). */
  mount: string;
  total_mb: number;
}

/** Why a call did not succeed: one of six `ErrorKind`s, a sentence for a
 * person, the finer cause where there is one, and the desk it concerned.
 * 
 * Its serde form is the object inside `gaiadesk-cli`'s `--json` error
 * envelope (`ErrorEnvelope`): `{"kind", "message", "reason"?, "desk"?}`. */
export interface Error {
  /** The desk it concerned, when there was one. */
  desk?: string | null;
  kind: ErrorKind;
  message: string;
  /** The finer cause: `offline`, `unknown_desk`, `not_online`, `network`,
   * `not_signed_in`, `timeout`, `local`, … */
  reason?: string | null;
}

/** `{"error": {…}}` — what every `--json` command prints when it fails. */
export interface ErrorEnvelope {
  error: Error;
}

/** The six kinds a program branches on. Stable: a new kind would be a
 * breaking change, so match with a wildcard arm anyway. */
export type ErrorKind = "usage" | "refused" | "unreachable" | "connection_lost" | "failed" | "protocol";

/** One event of a streamed command (`Desk::exec_stream`) —
 * `gaiadesk-cli exec --json-stream` prints one per line (all but `note`). */
export type ExecEvent = {
  data: string;
  event: "stdout";
} | {
  data: string;
  event: "stderr";
} | {
  event: "note";
  message: string;
} | (ExecExit & {
  event: "exit";
}) | {
  error: Error;
  event: "error";
  exit: number;
};

/** `ExecResult` without the output — the last event of a stream. */
export interface ExecExit {
  desk: string;
  duration_ms: number;
  error?: Error | null;
  exit: number;
  mode?: string | null;
  notes: Array<string>;
  remote_code?: number | null;
  route?: string | null;
  shell?: string | null;
  timed_out: boolean;
}

/** How one command ended — `gaiadesk-cli exec --json`'s object. */
export interface ExecResult {
  desk: string;
  duration_ms: number;
  /** `null` when it ran and ended on its own. */
  error?: Error | null;
  /** What `gaiadesk-cli exec` exits with: the program's code (0-255), 124
   * timed out, 130 interrupted, 254 refused, 255 not reached. */
  exit: number;
  /** `pipes`, or `terminal` on a desk from before plain pipes. */
  mode?: string | null;
  /** This client's own lines about the run. */
  notes: Array<string>;
  /** The program's own code (`null`: it never ran). */
  remote_code?: number | null;
  /** `LAN`, `Mesh`, `the GaiaDesk server` (`null`: never reached). */
  route?: string | null;
  /** The shell the desk actually used (`null`: it did not say). */
  shell?: string | null;
  stderr: string;
  stdout: string;
  timed_out: boolean;
  /** More than 16 MB of a stream was dropped. */
  truncated: boolean;
}

/** One command to run on a desk (`Desk::exec`).
 * 
 * `command` is ONE command line, given to the shell verbatim; `argv` is an
 * argument vector, each entry quoted for the shell so the program receives
 * exactly it. Build it with `ExecSpec::command` or `ExecSpec::argv`. */
export interface ExecSpec {
  argv?: Array<string>;
  command?: string | null;
  /** The directory it starts in on the desk (relative: from the desk
   * user's home, or a confined token's directory). */
  cwd?: string | null;
  /** Environment variables for it, on top of the desk's (sent in the
   * request, never logged). */
  env?: Record<string, string>;
  shell?: Shell;
  /** Text for its stdin, then end of input. Absent: stdin is closed (the
   * null device), unless `ExecInput` feeds it. */
  stdin?: string | null;
  /** Stop it after this many seconds (`0`: no limit; absent: 30 minutes). */
  timeout_secs?: number | null;
}

/** Forwards that are running (`Desk::forward_start`). */
export interface Forward {
  desk: string;
  forward_id: string;
  listening: Array<ForwardListening>;
}

/** One port listening (`forward --json`'s `{"event":"listening",…}`). */
export interface ForwardListening {
  desk: string;
  local_port: number;
  remote_host: string;
  remote_port: number;
}

/** One port to forward: `localhost:<local_port>` here → `<remote_host>:<remote_port>` as the desk reaches it. */
export interface ForwardSpec {
  /** The localhost port here (`0`: any free one). */
  local_port: number;
  /** Where the DESK connects (default: itself, `127.0.0.1`). */
  remote_host: string;
  remote_port: number;
}

/** A forward that ended on purpose (`Client::forward_stop`). */
export interface ForwardStopped {
  forward_id: string;
  local_ports: Array<number>;
}

/** `whoami --json`; `devices --json`'s `identity`. */
export interface Identity {
  /** The account's email (`null`: not signed in, or the server could not
   * say). */
  account?: string | null;
  /** `app`, `login`, `token` or `none`; from the hosted API (`GET
   * /v1/desks`), `api_key` or `session`. */
  source: string;
}

/** A background job on a desk. */
export interface Job {
  /** Who started it: the token's name, or `owner` for a person. */
  by?: string;
  command: string;
  ended_at_ms?: number | null;
  /** How the desk enforces them, one line each, in its own words — and
   * what it could not do here (e.g. "cgroups v2 not available: …"). */
  enforcement?: Array<string>;
  exit_code?: number | null;
  /** The caps and keep-awake it runs under, as the desk applied them
   * (`keep_awake` resolved against the desk's default). `None` from a desk
   * before job limits, and for a job started with none. */
  limits?: JobLimits | null;
  /** Bytes of output kept (current log plus its one rotated predecessor). */
  log_bytes?: number;
  name: string;
  pid?: number | null;
  /** Why it ended as it did, as a machine reads it, when the desk knows:
   * `blocked_by_os_policy` — Windows Smart App Control or WDAC refused
   * to start a program it ran (its `state` then says so in words). */
  reason?: string | null;
  started_at_ms: number;
  /** `running`, `exited`, `killed`, or `lost` (it was running when the
   * GaiaDesk host restarted and its end could not be observed). */
  state: string;
}

/** What a background job may use, and whether the desk stays awake for it
 * (`DataMessage::JobStart`'s `limits`). Every field optional and
 * off the wire when unset, so a start without limits is byte for byte what
 * it was. A desk lists `feature::JOB_LIMITS` when it enforces them;
 * a desk before that ignores the field, which is why a CLI refuses to send
 * caps to one. */
export interface JobLimits {
  /** At most this share of the whole machine's CPU, 1–100. */
  cpu_percent?: number | null;
  /** Hold off idle sleep while the job runs. `None`: the desk's default. */
  keep_awake?: boolean | null;
  /** At most this much memory for the job and everything it starts, MB. */
  mem_mb?: number | null;
  /** `low`, `normal` or `high`. */
  priority?: string | null;
}

/** `ps --json`. */
export interface JobList {
  jobs: Array<Job>;
}

/** One event of a followed job's output (`logs -f --json`). */
export type JobLogEvent = {
  data: string;
  event: "output";
} | {
  event: "end";
  job: Job;
} | {
  event: "interrupted";
} | {
  error: Error;
  event: "error";
};

/** `logs --json`: a job and the end of its output. */
export interface JobLogs {
  job: Job;
  output: string;
}

/** A background job to start (`Desk::run_job`). */
export interface JobSpec {
  /** ONE entry is the command line, verbatim for the desk's shell (`sh -c`,
   * `cmd /c`); several are words, each quoted for THAT desk's shell. */
  command: Array<string>;
  cwd?: string | null;
  /** Environment variables for it (never logged). */
  env?: Record<string, string>;
  limits?: JobLimits;
  /** Letters, digits, `.`, `_`, `-`: how `jobs`, `job_logs` and `kill_job`
   * find it. */
  name: string;
  /** The shell that runs it (absent: the desk's job shell — `sh -c`,
   * `cmd /c`). `none` is not one: a job is a command line. */
  shell?: Shell | null;
}

/** How a wait for a job ended (`Desk::wait_job`): the job as it
 * ended — or, `timed_out`, as it stands, still running. (`gaiadesk-cli
 * wait --json` prints `job`.) */
export interface JobWaitResult {
  job: Job;
  timed_out: boolean;
}

/** `measure --json`. */
export interface Measurement {
  clock_offset_ms?: number | null;
  clock_uncertainty_ms?: number | null;
  desk: string;
  rtt_ms?: RoundTrip | null;
  sent: number;
}

/** `mesh ip`: one desk's address; `renamed_to` when the id asked for is a
 * desk's old one (it answers on Mesh for 7 days after a change). */
export interface MeshIp {
  desk_id: string;
  mesh_ip: string;
  renamed_to?: string | null;
}

/** A desk's row in `mesh status`: its id (the Mesh node name IS the desk id)
 * and its stable Mesh address. */
export interface MeshPeer {
  desk_id: string;
  mesh_ip?: string | null;
  online: boolean;
  os: string;
}

/** This machine on the Mesh. */
export interface MeshSelf {
  desk_id: string;
  mesh_ip?: string | null;
}

/** `mesh status`: this machine and its peers. */
export interface MeshStatus {
  peers: Array<MeshPeer>;
  self?: MeshSelf | null;
}

/** `token create --out <file> --json`: the tokens minted, and the file their
 * secrets were written to (0600, one per line). */
export interface MintFileResult {
  file: string;
  tokens: Array<MintedTokenFiled>;
}

/** `token create --json` (several desks: one token each). */
export interface MintResult {
  tokens: Array<MintedToken>;
}

/** An agent token to mint (`Desk::mint_token`). */
export interface MintSpec {
  /** The directory on the desk the token's work is confined to. */
  cwd?: string | null;
  expires_secs: number;
  /** Its work runs as the desk's low-privilege agent user. */
  low_priv?: boolean;
  name: string;
  /** `exec`, `shell`, `cp`, `forward`, `jobs`, `screen`. */
  scopes: Array<string>;
}

/** One minted token. `secret` is the token itself — shown once. */
export interface MintedToken {
  desk: string;
  secret: string;
  token: TokenInfo;
}

/** One token written to a file (`token create --out --json`): its desk and
 * what it allows — never the secret, which is only in the file. */
export interface MintedTokenFiled {
  desk: string;
  token: TokenInfo;
}

/** One desk's probe. */
export interface ProbeResult {
  connect_ms?: number | null;
  /** Whether it was dialled at all (no credential for it: not). */
  dialled: boolean;
  error?: string | null;
  hostname?: string | null;
  /** Why not: a `dial_stage::kind`, an error kind,
   * `agent_not_answering` or `no_credential`. */
  kind?: string | null;
  /** Connected AND its agent answered a round trip. */
  ok: boolean;
  os?: string | null;
  route?: string | null;
  rtt_ms?: number | null;
}

/** A connect that did not. */
export interface ReachFailure {
  at: number;
  /** A stable key: a `dial_stage::kind` or an error kind. */
  kind: string;
  /** One line, as the CLI said it. */
  message: string;
}

/** A connect that worked. */
export interface ReachSuccess {
  /** Seconds since the epoch. */
  at: number;
  /** How long the connect took, ms. */
  connect_ms?: number | null;
  /** `LAN`, `Mesh`, `the GaiaDesk server`. */
  route: string;
  /** A data-plane round trip measured on it (`devices --probe`), ms. */
  rtt_ms?: number | null;
}

/** `token revoke --json`. */
export interface Revoked {
  revoked: string;
  stopped_sessions: number;
}

/** Round trips, ms. */
export interface RoundTrip {
  max: number;
  n: number;
  p50: number;
  p95: number;
}

/** A picture of the screen. */
export interface ScreenImage {
  data_base64: string;
  height?: number | null;
  /** `image/png`. */
  media_type: string;
  width?: number | null;
}

/** What one screen action returned: words, and a picture when it took one. */
export interface ScreenResult {
  image?: ScreenImage | null;
  text: string;
}

export interface ScreenSize {
  height: number;
  width: number;
}

/** Which shell runs a command on the desk. */
export type Shell = "default" | "none" | "sh" | "bash" | "zsh" | "cmd" | "pwsh" | "powershell";

/** `stats --json`: the desk's own figures. */
export interface StatsReport {
  /** Busy share of the whole machine, 0–100, over a short sample. */
  cpu_percent: number;
  /** Logical CPUs. */
  cpus: number;
  desk: string;
  /** Every mounted volume worth listing, with its free space. */
  disks?: Array<DiskStat>;
  hostname: string;
  /** Background jobs (`gaiadesk-cli run --detach`) running now. */
  jobs_running: number;
  /** 1, 5 and 15 minute load averages. `None` where the OS has none (Windows). */
  load?: Array<number> | null;
  /** What programs can still have without swapping ("available"). */
  mem_free_mb: number;
  mem_total_mb: number;
  /** `macos`, `windows`, `linux` (`std::env::consts::OS`). */
  os: string;
  /** The OS's own name and version (`macOS 15.1`, `Windows 11 (26100)`). */
  os_version?: string;
  uptime_secs: number;
}

/** One agent token as its desk's owner sees it: everything but the secret. */
export interface TokenInfo {
  /** The directory this token's work is confined to: its commands, shells
   * and jobs start there, and every path it copies must resolve inside it
   * (links resolved first). `None`: not confined. */
  cwd?: string | null;
  expires_at_ms: number;
  /** The token's non-secret id (a digest of its stored hash). */
  id: string;
  issued_at_ms: number;
  label: string;
  last_used_ms?: number | null;
  /** Its commands, shells and jobs run as the desk's low-privilege agent
   * user (set on the desk), or are refused — never as the desk's own user. */
  low_priv?: boolean;
  revoked?: boolean;
  /** What it may do: `screen`, `exec`, `cp`, `forward`, `jobs`. Empty for a
   * token from before scopes, which is a screen (Agent Access) token. */
  scopes?: Array<string>;
}

/** `token list --json`. */
export interface TokenList {
  tokens: Array<TokenInfo>;
}

/** `--version --json`. */
export interface VersionInfo {
  features: Array<string>;
  mcp_protocol_versions: Array<string>;
  name: string;
  version: string;
}
